from django.core.management.base import BaseCommand
from mirs.models import Tema, Subtema, Tipo, Submotivo, Subtipo, Medio, Canal, Estacion, ProgramaRadio, ProgramaTV, RedSocial


class Command(BaseCommand):
    help = 'Populate data in tables'

    def handle(self, *args, **kwargs):
        temas = ['C5', '911', 'MARCHAS Y BLOQUEOS',
                 'JEFA DE GOBIERNO', 'OTROS', 'EMERGENCIAS Y SEGURIDAD']
        subtemas = [
            "Alerta Amber",
            "AMLO",
            "Atención prehospitalaria (ambulancias)",
            "Atentados en estados y países",
            "Bloqueo",
            "Botón auxilio",
            "Captado por cámaras",
            "Claudia Sheinbaum",
            "Concentración",
            "Damnificados del sismo",
            "Dependencias",
            "Entrevista",
            "Estadísticas de la CDMX",
            "Evento Deportivo",
            "Juan Manuel",
            "Manifestantes",
            "Maratón",
            "Marchas con afectación vial",
            "Marchas sin afectación vial",
            "Mención 911",
            "Menciones de C5",
            "No sirven cámaras",
            "Queja de servicio",
            "Sismo de intensidad en otro país",
            "SSC-CDMX"
        ]

        tipos = ['Delito', 'Denuncia', 'Emergencia', 'Falta Cívica',
                 'Información', 'Servicio', 'Urgencias Médicas']
        submotivos = [
            "A policía",
            "Casa habitación",
            "Negocio",
            "Persona",
            "Servidor público",
            "Violencia intrafamiliar",
            "Otros",
            "A inmueble",
            "Agresión",
            "Abandonado",
            "Arma blanca",
            "Arma contusa",
            "Arma de fuego",
            "Enterrado",
            "Feto",
            "Homicidio",
            "Quemado o Electrocutado",
            "Riña o Golpes",
            "Traslado de droga o estupefacientes",
            "Venta o distribución de droga o estupefacientes",
            "A la Nación - Vías de comunicación",
            "Instalaciones gubernamentales",
            "Propiedad ajena",
            "Sistema Tecnológico de Videovigilancia",
            "Extorsión",
            "Fraude",
            "Fuga de reos",
            "Invasión de Predio",
            "Motín",
            "Tala clandestina",
            "Venta de Pirotecnia",
            "Venta ilegal de combustibles",
            "Toma clandestina",
            "Sustracción ilegal de combustible",
            "Almacenamiento ilegal de combustible",
            "Transporte ilegal de combustible",
            "Accidente automovilístico",
            "Allanamiento",
            "Atropellamiento",
            "Daños",
            "Delitos Sexuales",
            "Robo",
            "Disparos",
            "Linchamiento",
            "Quema de pirotecnia",
            "Riña",
            "Agresión a funcionarios",
            "Agresión a inmueble",
            "Compra de votos",
            "Credencial apócrifa",
            "Impedir instalación",
            "Proselitismo",
            "Quema de urnas o boletas",
            "Quema del paquete electoral",
            "Retiro de propaganda",
            "Robo de urnas o boletas",
            "Robo del paquete electoral",
            "Por arma de fuego",
            "Retención de menores",
            "Secuestro",
            "Secuestro express",
            "A taxista",
            "Animales",
            "Auto partes - Objetos personales",
            "Automovilista",
            "Bancos",
            "Cable",
            "Cajero automático",
            "Camioneta de valores",
            "Casa habitación con violencia",
            "Casa habitación sin violencia",
            "Bienes gubernamentales (Coladeras Cable)",
            "Cuentahabiente",
            "Escuela",
            "Establecimiento con violencia",
            "Establecimiento sin violencia",
            "Institución Pública",
            "Pasajero transporte público",
            "Repartidor",
            "Transeúnte",
            "Transporte de carga o mercancías",
            "Vehículo con volencia",
            "Vehículo sin violencia",
            "Tarjetahabiente",
            "Pasajero transporte público - Metro",
            "Pasajero transporte público - Metrobus",
            "Pasajero transporte público - Transportes Eléctricos",
            "Pasajero transporte público - M1",
            "Pasajero transporte público - Microbus",
            "Pasajero transporte público - APP",
            "Transporte público - Taxi",
            "Abuso",
            "Violación",
            "Otros - Vejaciones",
            "Menor en riesgo",
            "Alerta de TI",
            "Acuático",
            "Aéreo",
            "Choque sin lesionados",
            "Ferroviario",
            "Persona atrapada",
            "Persona desbarrancada",
            "Sumersión",
            "Vehículo atrapado",
            "Vehículo desbarrancado",
            "Volcadura",
            "Bomba",
            "Atragantamiento",
            "Atropellado",
            "Caída",
            "Estrangulado",
            "Intoxicación",
            "Muerte causa ignorada",
            "Natural",
            "Suicidio",
            "Suspendido",
            "Vías del metro",
            "Agrietamiento",
            "Caída de ceniza",
            "Caída de rayo",
            "Derrumbe",
            "Desborde de Canal - Río - Presa",
            "Deslave",
            "Hundimiento",
            "Inundación",
            "Socavón",
            "Zona sin energía eléctrica",
            "Afectación inmueble",
            "Afectación vehículo",
            "Caída de rama",
            "Cilindro de gas",
            "Gas natural",
            "Material o sustancia en pavimento",
            "Olor a gas - Combustible químicos",
            "Petróleo y derivados o ductos",
            "Pipa de gas",
            "Productos químicos",
            "Tanque estacionario",
            "Artefacto explosivo",
            "Ductos",
            "Edificio",
            "Gasolinera",
            "Industria",
            "Instalaciones de gobierno",
            "Instalaciones PEMEX",
            "Mufas",
            "Negocio ? Plaza Comercial - Mercado",
            "Pipa",
            "Polvorín clandestino",
            "Transformador",
            "Vehículo",
            "Árbol",
            "Forestal",
            "Lote baldío",
            "Quema de basura",
            "Quema de pastizal",
            "Reporte ANPR",
            "Enjambre",
            "911 CDMX - Llamada Silenciosa",
            "Acoso",
            "Acoso en transporte público",
            "Crisis nerviosa",
            "Explosión",
            "Explosión de transformador",
            "Fuga de gas doméstico",
            "Fuga de gas natural",
            "Incendio",
            "Persona lesionada",
            "Desborde de Canal-Río-Presa",
            "Estructura en riesgo de colapso",
            "Fuga de agua",
            "Fuga de combustible",
            "Persona atrapada - Escombros",
            "Persona atrapada - Elevador",
            "Persona Atropellada",
            "Falta energía eléctrica",
            "Choque con lesionados",
            "Choque con prensados",
            "Comercio informal",
            "Drogados",
            "Ebrios",
            "Faltas a la moral",
            "Fisiológica",
            "Franeleros",
            "Grafitis",
            "Prostitución",
            "Tirar basura en vía pública",
            "Consumo de droga o estupefacientes",
            "Arrancones",
            "Bloqueos",
            "Desperdicio de agua",
            "Escándalo",
            "Fiestas",
            "Jugadores",
            "Marcha de personas",
            "Simulacro",
            "Animal",
            "Arma - Cartucho",
            "De objeto",
            "Órganos - Tejido",
            "Vehículo abandonado con reporte en ANPR",
            "Caída de árbol",
            "Caída de cables",
            "Caída de espectacular",
            "Caída de poste",
            "Desprendimiento lona de espectacular",
            "Encharcamiento",
            "Árbol ladeado",
            "Poste ladeado",
            "Caída de barda",
            "Hechos",
            "Maltrato animal",
            "Maltrato - Discriminación",
            "Olor Fétido - Manchas hemáticas en inmueble",
            "Persona desaparecida",
            "Persona en riesgo",
            "Persona sospechosa",
            "Reventa",
            "Ruptura de Sellos",
            "Vehículo con manchas hemáticas - Olor fétido",
            "Aguas negras",
            "Agua potable",
            "Concentración de personas",
            "Agradecimiento servicio",
            "Apoyo a policía",
            "Eventos dentro de las instalaciones del Metro",
            "Eventos especiales",
            "Operativos especiales",
            "Queja contra operador",
            "Abastecimiento de agua",
            "Alarma activada",
            "Animales peligrosos",
            "Apoyo para desalojo",
            "Apoyo vial - Embotellamiento",
            "Apoyo vial - Semáforos descompuestos",
            "Baches",
            "Coladera o registro sin tapa",
            "Corto cables - Transformador",
            "Corto circuito - Mufa",
            "Denuncia Profeco",
            "Desalojo simulacro",
            "Entrevista ciudadana",
            "Falla en STV o marco ANPR",
            "Falta de agua",
            "Peregrinación",
            "Persona extraviada",
            "Reporte de vehículo vía GPS",
            "Reporte de vehículo vía Radio",
            "Reporte de vehículo vía Radio Estado de México",
            "Transporte de carga fuera de horario",
            "Solicitud de escolta",
            "Vehículo chatarra",
            "Vehículo descompuesto",
            "Vehículo obstruyendo",
            "Vehículo recuperado",
            "Evacuación",
            "Evaluación - Casa habitación",
            "Evaluación - Unidad habitacional",
            "Evaluación - Edificio",
            "Evaluación - Edificio de gobierno",
            "Evaluación - Escuela",
            "Poste o árbol ladeado",
            "Luminarias",
            "Falla Altavoces",
            "Motociclista",
            "Electrocutado",
            "Intento de suicidio",
            "Picadura o Mordedura",
            "Policía",
            "Por arma blanca",
            "Por golpes",
            "Por herramienta o maquinaria",
            "Por objeto contuso",
            "Prácticas deportivas",
            "Prensado",
            "Quemadura",
            "Ahogamiento",
            "Amenaza de aborto",
            "Asfixia",
            "Convulsiones",
            "Dolor",
            "Enfermo",
            "Hemorragia",
            "Inconsciente",
            "Infarto",
            "Intoxicado",
            "Trabajo de Parto - Alumbramiento",
            "Otros - Luminarias",
            "Otros - Poda de árbol"
        ]

        subtipos = ['Agresión', 'Amenaza', 'Cadáver', 'Contra la salud', 'Daños', 'Denuncia', 'Detención Ciudadana', 'Disturbio', 'Electorales', 'Lesionado', 'Privación de la Libertad', 'Robo', 'Sexuales',
                    'Accidente', 'Daños por Fenómeno natural o Tercero', 'Derrame o Fuga', 'Explosión', 'Incendio', 'Otros', 'Servicios', 'Sismo', 'Administrativas', 'Abandono', 'Daños por Fenómeno natural o Tercero', 'Médicos']
        medios = ['Periódico', 'Radio', 'TV', 'Red Social']
        canales = ['Canal 1', 'Canal 2', 'Canal 3']
        estaciones = ['40.1', '125 IZZI','Canal 28','Canal 4','3.1','120 IZZI','11.1','Canal 6','2.1','4.1','1.1','7.1']
        programas_radio = ['88.9', '103.3', '104.1', '90.5', '96.9', '102.5', '1110 AM', '790 AM', '1150 AM', '92.1 FM']
        programas_tv = [
    'Así Amanece',
    'Es de Mañana',
    'Noticias de ida y vuelta',
    'Es Noticia',
    'Noticias todo el Tiempo',
    'Lo Que No Se Dijo',
    'Efekto Noticias Todo el Tiempo',
    'Capital a Debate',
    'Titulares de la mañana',
    'Las Noticias de las 5:00 Hrs.',
    'Estrictamente personal',
    'Expreso de la mañana',
    'Por las mañanas',
    'Paralelo 23',
    'En la mira',
    'Noticias MX',
    'A las 3',
    'Noticias de las 16:00 Hrs.',
    'Noticias de las 17:00 Hrs.',
    'Noticias de las 18:00 Hrs.',
    'Noticias de las 19:00 Hrs.',
    'Noticias de las 20:00 Hrs.',
    'Hora 21',
    'Es la hora de opinar',
    'Las noticias',
    'Imagen Noticias con Francisco Zea',
    'Imagen Noticias con Yuridia Sierra',
    'Imagen Noticias con Ciro Gómez Leyva',
    'Milenio Noticias',
    'Milenio Noticias de la Noche',
    'Con Puig a las Diez',
    'Once Noticias Matutino',
    'Once Noticias',
    'Once Noticias Nocturno',
    'Telediario',
    'Las Noticias con Danielle Dithurbide',
    'Despierta con Loret',
    'Al aire',
    'El Noticiero con Karla Iberia',
    'En Punto',
    'Tercer Grado',
    'Las Noticias de las 05:00',
    'Matutino Express',
    'Las Noticias de las 14:30',
    'Las Noticias de las 16:30',
    'Las Noticias de las 17:00',
    'Las Noticias de las 18:00',
    'En una hora',
    'Agenda Pública',
    'Buenos Días Metrópoli'
]

        redes_sociales = ['Twitter', 'Facebook', 'Instagram']

        for tema in temas:
            Tema.objects.get_or_create(nombre=tema)

        for subtema in subtemas:
            Subtema.objects.get_or_create(nombre=subtema)

        for tipo in tipos:
            Tipo.objects.get_or_create(nombre=tipo)

        for submotivo in submotivos:
            Submotivo.objects.get_or_create(nombre=submotivo)

        for subtipo in subtipos:
            Subtipo.objects.get_or_create(nombre=subtipo)

        for medio in medios:
            Medio.objects.get_or_create(nombre=medio)

        for canal in canales:
            Canal.objects.get_or_create(nombre=canal)

        for estacion in estaciones:
            Estacion.objects.get_or_create(nombre=estacion)

        for programa_radio in programas_radio:
            ProgramaRadio.objects.get_or_create(nombre=programa_radio)

        for programa_tv in programas_tv:
            ProgramaTV.objects.get_or_create(nombre=programa_tv)

        for red_social in redes_sociales:
            RedSocial.objects.get_or_create(nombre=red_social)

        self.stdout.write(self.style.SUCCESS(
            'Successfully populated the data'))
