# Generated by Django 4.2.4 on 2023-08-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mirs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="noticia",
            name="polaridad",
            field=models.CharField(
                choices=[
                    ("positivo", "Positivo"),
                    ("neutro", "Neutro"),
                    ("negativo", "Negativo"),
                ],
                max_length=10,
            ),
        ),
    ]
